- name: Set authorized key taken from file
  authorized_key:
    user: ec2-user
    state: present
    key: '{{ item }}'
  with_file:
    - public_keys/ec2_user.pub

- name: Copy minio binary
  copy:
    src: minio
    dest: /minio

- name: Change minio binary permission
  file:
    dest: /minio
    mode: +x