Vagrant.configure("2") do |config|
    config.vm.box = "gbailey/amzn2"
    config.vm.box_version = "20200508.0.0"

    config.vbguest.auto_update = false
    # do NOT download the iso file from a webserver
    config.vbguest.no_remote = true

    config.ssh.insert_key = false
    config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']

    config.vm.provision :ansible do |ansible|
        ansible.inventory_path = "ansible-provisioning/inventory"
        ansible.playbook = "ansible-provisioning/playbook.yml"
    end

    config.vm.network "forwarded_port", guest: 8787, host: 8787
    config.vm.network "forwarded_port", guest: 3838, host: 3838
    config.vm.network "forwarded_port", guest: 8000, host: 8000

    config.vm.network "private_network", ip: "192.168.50.4"

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
end